"""Structured remediation advice templates keyed by vulnerability category.

Each template maps a vulnerability archetype (derived from static analysis signals)
to a CVSS 3.1 score, CWE identifier, root-cause explanation, concrete fix code, and
verification steps.
"""

from __future__ import annotations

from typing import Any

# ── Vulnerability archetype → structured remediation ──────────────────────

REMEDIATION_TEMPLATES: dict[str, dict[str, Any]] = {
    # ── Command Injection ────────────────────────────────────────────
    "COMMAND_INJECTION_GOHED_SYSTEM": {
        "title_pattern": "system",
        "cwe_id": "CWE-78",
        "cwe_name": "OS Command Injection",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "The firmware web application passes user-controlled input directly to "
            "the C standard library `system()` function (or a wrapper such as "
            "`doSystem` / `doSystembk` in the GoAhead webserver). No input "
            "sanitization, allowlisting, or shell metacharacter escaping is "
            "performed before the call, allowing an attacker to inject arbitrary "
            "shell commands that execute with the privileges of the web server "
            "process (typically root on embedded devices)."
        ),
        "attack_scenario": (
            "An unauthenticated (or weakly authenticated) attacker sends a crafted "
            "HTTP request to a CGI endpoint or ASP handler that flows into a "
            "`doSystem`-family call. Shell metacharacters (`;`, `|`, `&&`, `$()`, "
            "backticks) are not stripped, so a payload such as "
            "`; telnetd -l /bin/sh -p 9999;` spawns a root bind shell."
        ),
        "remediation_steps": [
            "Replace all `system()` / `popen()` calls with `execv()` or `execve()` family calls that do not invoke a shell.",
            "If shell invocation is unavoidable, use a fixed argument list and pass user input only as positional arguments — never concatenate into a command string.",
            "Apply input validation: allowlist acceptable characters (alphanumeric + limited safe punctuation) at every CGI/ASP entry point.",
            "Drop privileges after binding the network socket — the web server should not run as root.",
            "Compile with `-fstack-protector-strong` and `-D_FORTIFY_SOURCE=2` as defense-in-depth.",
        ],
        "fix_code_example": (
            "/* BEFORE (vulnerable) */\n"
            'char cmd[256];\n'
            'snprintf(cmd, sizeof(cmd), "config_set %s", user_input);\n'
            "system(cmd);  // ← shell metacharacters in user_input → RCE\n"
            "\n"
            "/* AFTER (fixed) */\n"
            "pid_t pid = fork();\n"
            "if (pid == 0) {\n"
            '    const char *argv[] = {"/usr/sbin/config_set", user_input, NULL};\n'
            "    execv(argv[0], (char *const *)argv);\n"
            "    _exit(127);\n"
            "}\n"
            "/* parent: waitpid + validate exit status */"
        ),
        "verification": [
            "Send a request with a benign timing payload: `; sleep 10;` — if the response is delayed by 10 seconds, injection is confirmed.",
            "After applying the fix, repeat the same payload and confirm the delay is absent.",
            "Run a static analysis tool (e.g., semgrep rule for `system(` with variable arguments) across the rebuilt binary.",
        ],
    },

    "COMMAND_INJECTION_UPLOAD_HANDLER": {
        "title_pattern": "upload",
        "cwe_id": "CWE-78",
        "cwe_name": "OS Command Injection",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "An upload handler (CGI binary or ASP script) passes attacker-supplied "
            "filenames, paths, or file content directly into system commands — "
            "typically via `system()`, `popen()`, or backtick expansion in shell "
            "scripts. The `import_5g`, `upload_settings.cgi`, or similar endpoints "
            "decode the upload and then invoke external tools with unsanitized "
            "user-controlled arguments."
        ),
        "attack_scenario": (
            "An attacker uploads a crafted file whose name or content contains shell "
            "metacharacters. When the firmware processes the upload (e.g., to import "
            "configuration or flash a bootloader), the injected commands execute "
            "with root privileges."
        ),
        "remediation_steps": [
            "Never construct shell command strings from user-supplied filenames.",
            "Use fixed temporary paths generated by `mkstemp()` or equivalent.",
            "Validate uploaded file content against an expected schema before any processing.",
            "Execute post-upload processing binaries directly via `execv()`, not via shell.",
        ],
        "fix_code_example": (
            "/* BEFORE (vulnerable shell script) */\n"
            '#!/bin/sh\n'
            'tar xzf /var/webupload/$UPLOADED_FILE -C /etc_ro/\n'
            "# ← $UPLOADED_FILE can contain `; rm -rf / ;`\n"
            "\n"
            "/* AFTER (fixed C handler) */\n"
            'char safe_path[PATH_MAX];\n'
            'snprintf(safe_path, sizeof(safe_path),\n'
            '         "/tmp/upload_%s", basename(user_filename));\n'
            "// Validate extension, magic bytes, and size before processing\n"
            "if (!validate_upload(safe_path)) { cleanup(); return -1; }\n"
            "pid_t pid = fork();\n"
            "if (pid == 0) {\n"
            '    execl("/usr/sbin/config_import", "config_import", safe_path, NULL);\n'
            "    _exit(127);\n"
            "}"
        ),
        "verification": [
            "Upload a file named `; id > /www/pwned.txt ;.cfg` and check whether `/www/pwned.txt` is created.",
            "After the fix, confirm the upload is rejected or the filename is sanitized.",
        ],
    },

    # ── Hardcoded / Default Credentials ─────────────────────────────
    "HARDCODED_CREDENTIALS": {
        "title_pattern": "credential",
        "cwe_id": "CWE-798",
        "cwe_name": "Use of Hard-coded Credentials",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "The firmware ships with hardcoded or easily derivable credentials "
            "(e.g., `admin:admin`, `root:12345`, or values read from NVRAM "
            "defaults such as `nvram_get 2860 Login` / `nvram_get 2860 Password`). "
            "These credentials are embedded in boot scripts, CGI handlers, or "
            "compiled binaries and are identical across all devices running the "
            "same firmware version."
        ),
        "attack_scenario": (
            "An attacker retrieves the firmware image from the vendor website, "
            "extracts the SquashFS filesystem, and reads the default credentials "
            "from `/etc_ro/rcS`, `/sbin/internet.sh`, or `/etc/passwd`. These "
            "credentials grant administrative access to the web interface, Telnet, "
            "or SSH on every deployed device."
        ),
        "remediation_steps": [
            "Remove all hardcoded credentials from boot scripts and binaries.",
            "Require a unique, per-device password set during first boot or manufacturing.",
            "Use a secure element (TPM/secure boot) to store device-specific secrets.",
            "Enforce password complexity requirements and lockout after failed attempts.",
            "Disable Telnet by default; require explicit user opt-in with a strong password.",
        ],
        "fix_code_example": (
            "/* BEFORE (vulnerable) — /sbin/internet.sh */\n"
            'login=`nvram_get 2860 Login`     # default: "admin"\n'
            'pass=`nvram_get 2860 Password`    # default: "admin"\n'
            'echo "$login::0:0:Administrator:/:/bin/sh" > /etc/passwd\n'
            'chpasswd.sh $login $pass\n'
            "\n"
            "/* AFTER (fixed) */\n"
            "# Check whether a unique device password has been provisioned.\n"
            'if ! is_device_provisioned; then\n'
            '    echo "ERROR: Device not provisioned. Access denied." >&2\n'
            '    exit 1\n'
            "fi\n"
            "# Use a per-device secret stored in a secure keystore.\n"
            'login=$(secure_keystore_read "admin_user")\n'
            'pass=$(secure_keystore_read "admin_pass")\n'
            'if [ -z "$pass" ] || [ ${#pass} -lt 12 ]; then\n'
            '    echo "ERROR: Weak or missing admin password." >&2\n'
            '    exit 1\n'
            "fi"
        ),
        "verification": [
            "Extract the firmware and confirm no plaintext credentials remain in init scripts.",
            "Factory-reset the device and confirm Telnet/SSH are disabled until a unique password is set.",
            "Attempt to log in with known default credentials — access must be denied.",
        ],
    },

    "HARDCODED_CREDENTIALS_TELNET": {
        "title_pattern": "telnet",
        "cwe_id": "CWE-798",
        "cwe_name": "Use of Hard-coded Credentials",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "The `/etc_ro/rcS` boot script unconditionally launches `telnetd` during "
            "initialization, and the associated web management page "
            "(`/etc_ro/web/d_telnet.asp` → `form2Telnet.cgi`) toggles the Telnet "
            "state through NVRAM values. When combined with default credentials "
            "embedded in `/sbin/internet.sh`, an attacker can enable Telnet "
            "remotely and log in with root privileges."
        ),
        "attack_scenario": (
            "An attacker sends a crafted request to `/goform/form2Telnet` setting "
            "`telnetEnabled=1`, then connects to port 23 with the default root "
            "credentials extracted from the firmware image."
        ),
        "remediation_steps": [
            "Remove the `telnetd` launch from `/etc_ro/rcS` — Telnet should never start unconditionally.",
            "Replace Telnet with SSH, and disable both by default.",
            "The `form2Telnet.cgi` endpoint must require strong re-authentication and must not accept unauthenticated requests.",
            "Add a physical button or hardware-backed enrollment flow to enable debug services.",
        ],
        "fix_code_example": (
            "/* BEFORE (vulnerable) — /etc_ro/rcS */\n"
            "# ...\n"
            "telnetd              # ← unconditional root shell exposure\n"
            "goahead &\n"
            "\n"
            "/* AFTER (fixed) */\n"
            "# Telnet is disabled by default; the debug shell requires\n"
            "# a signed token from the hardware security module.\n"
            'if hsm_debug_token_valid "telnet"; then\n'
            "    telnetd -l /bin/login   # ← still requires valid credentials\n"
            "fi"
        ),
        "verification": [
            "Boot the device and scan port 23 — it must be closed by default.",
            "Attempt to call `/goform/form2Telnet` without authentication — it must return 401/403.",
        ],
    },

    # ── Authentication Bypass ────────────────────────────────────────
    "AUTH_BYPASS_UPLOAD": {
        "title_pattern": "upload",
        "cwe_id": "CWE-306",
        "cwe_name": "Missing Authentication for Critical Function",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "One or more firmware upload handlers (e.g., `upload.cgi`, "
            "`upload_settings.cgi`, `upload_bootloader.cgi`) do not verify that "
            "the requester is authenticated before processing the upload. An "
            "attacker can upload a malicious configuration file or firmware image "
            "without any credentials."
        ),
        "attack_scenario": (
            "An unauthenticated attacker sends a POST request to "
            "`/cgi-bin/upload_settings.cgi` with a crafted configuration archive "
            "containing a reverse shell or credential-overwrite payload. The "
            "handler processes the upload and applies the malicious configuration, "
            "granting persistent access."
        ),
        "remediation_steps": [
            "Add a session validation check at the top of every CGI/ASP handler that mutates device state.",
            "Use a capability-based authorization model: each handler declares required capabilities, and the framework enforces them before dispatch.",
            "Implement CSRF protection (per-request tokens) even for authenticated endpoints.",
            "Log and alert on unauthenticated access attempts to privileged handlers.",
        ],
        "fix_code_example": (
            "/* BEFORE (vulnerable) — upload_settings.cgi */\n"
            "int main(void) {\n"
            "    handle_upload();   // ← no auth check\n"
            "    return 0;\n"
            "}\n"
            "\n"
            "/* AFTER (fixed) */\n"
            "int main(void) {\n"
            '    if (!session_is_authenticated() || !session_is_admin()) {\n'
            '        http_response(403, "Forbidden");\n'
            "        return -1;\n"
            "    }\n"
            '    if (!csrf_token_valid(get_cookie("csrf_token"))) {\n'
            '        http_response(403, "CSRF validation failed");\n'
            "        return -1;\n"
            "    }\n"
            "    handle_upload();\n"
            "    return 0;\n"
            "}"
        ),
        "verification": [
            "Send an unauthenticated POST to each upload endpoint — all must return 401/403.",
            "After the fix, repeat the same request with a valid session — it must succeed.",
        ],
    },

    "AUTH_BYPASS_CONFIG_EXPORT": {
        "title_pattern": "export",
        "cwe_id": "CWE-306",
        "cwe_name": "Missing Authentication for Critical Function",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "cvss_score": "7.5",
        "cvss_severity": "HIGH",
        "root_cause": (
            "The configuration export endpoint (`ExportSettings.sh` or "
            "`/cgi-bin/ExportSettings.sh`) dumps the full device configuration — "
            "including Wi-Fi passphrases, PPPoE credentials, and administrative "
            "tokens — without requiring authentication. An attacker can retrieve "
            "all device secrets in a single unauthenticated request."
        ),
        "attack_scenario": (
            "An attacker sends a GET request to `/cgi-bin/ExportSettings.sh` and "
            "receives a `config.img` file containing all NVRAM settings in plaintext, "
            "including administrator credentials."
        ),
        "remediation_steps": [
            "Require administrator authentication before serving the configuration export.",
            "Redact or encrypt sensitive fields (passwords, keys, tokens) in the export.",
            "Log every configuration export event with the authenticated user identity.",
        ],
        "fix_code_example": (
            "/* AFTER (fixed) — ExportSettings.sh wrapper */\n"
            'if ! session_is_admin; then\n'
            '    echo "Status: 403 Forbidden"\n'
            '    echo ""\n'
            "    exit 1\n"
            "fi\n"
            "# Redact secrets before export.\n"
            "ralink_init show 2860 | sed -E 's/(Password|Key)=.*/\\1=***REDACTED***/g'"
        ),
        "verification": [
            "Request `/cgi-bin/ExportSettings.sh` without a session cookie — must return 403.",
            "Request with a valid admin session — must return redacted configuration.",
        ],
    },

    # ── Insecure Configuration / Information Disclosure ──────────────
    "INSECURE_CONFIG_IMPORT": {
        "title_pattern": "import",
        "cwe_id": "CWE-15",
        "cwe_name": "External Control of System or Configuration Setting",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "The firmware accepts configuration import files without cryptographic "
            "signature verification. An attacker can craft a malicious configuration "
            "file that sets `Login` and `Password` NVRAM values, which are then "
            "materialized into `/etc/passwd` by `/sbin/internet.sh` at next boot."
        ),
        "attack_scenario": (
            "An attacker modifies the exported `config.img`, setting "
            "`Login=attacker` and `Password=evilpass`, then imports it via "
            "`/cgi-bin/upload_settings.cgi`. After reboot, the attacker has a "
            "root shell account."
        ),
        "remediation_steps": [
            "Digitally sign configuration archives with a device-specific or vendor key.",
            "Reject unsigned or signature-mismatched imports.",
            "Validate each imported setting against a schema — reject unexpected or dangerous keys.",
        ],
        "fix_code_example": (
            "/* AFTER (fixed) — signature check before import */\n"
            'if (!verify_ed25519_signature(config_file, config_file_sig)) {\n'
            '    syslog(LOG_ERR, "Config import rejected: invalid signature");\n'
            "    return -1;\n"
            "}"
        ),
        "verification": [
            "Import a modified `config.img` — the device must reject it.",
            "Import the original signed `config.img` — it must be accepted.",
        ],
    },

    # ── Buffer Overflow ──────────────────────────────────────────────
    "BUFFER_OVERFLOW_CGI": {
        "title_pattern": "overflow",
        "cwe_id": "CWE-120",
        "cwe_name": "Buffer Copy without Checking Size of Input",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8",
        "cvss_severity": "CRITICAL",
        "root_cause": (
            "A CGI handler or web server component copies user-supplied input "
            "into a fixed-size stack buffer using an unbounded function (e.g., "
            "`strcpy`, `sprintf`, `gets`). An attacker can overflow the buffer "
            "to overwrite the return address and gain arbitrary code execution."
        ),
        "attack_scenario": (
            "An attacker sends an oversized HTTP parameter or POST body to a CGI "
            "endpoint. The overflow corrupts the stack, allowing the attacker to "
            "redirect execution to shellcode placed in the payload."
        ),
        "remediation_steps": [
            "Replace all unbounded copy functions (`strcpy`, `sprintf`, `gets`, `strcat`) with bounded alternatives (`strncpy`, `snprintf`, `strncat`).",
            "Add explicit length checks before every memory copy operation.",
            "Compile with stack canaries (`-fstack-protector-all`) and DEP/NX.",
            "Enable ASLR if the platform supports it.",
        ],
        "fix_code_example": (
            "/* BEFORE (vulnerable) */\n"
            "char buf[256];\n"
            'strcpy(buf, getenv("QUERY_STRING"));  // ← unbounded\n'
            "\n"
            "/* AFTER (fixed) */\n"
            "char buf[256];\n"
            'const char *qs = getenv("QUERY_STRING");\n'
            "if (!qs || strlen(qs) >= sizeof(buf)) {\n"
            '    http_response(400, "Bad Request");\n'
            "    return -1;\n"
            "}\n"
            "strncpy(buf, qs, sizeof(buf) - 1);\n"
            "buf[sizeof(buf) - 1] = '\\0';"
        ),
        "verification": [
            "Send a request with a parameter exceeding 256 bytes — the server must return 400, not crash.",
            "Run a fuzzer (e.g., AFL++) against the CGI binary with the fix applied.",
        ],
    },

    # ── Format String ─────────────────────────────────────────────
    "FORMAT_STRING": {
        "title_pattern": "format string",
        "cwe_id": "CWE-134", "cwe_name": "Use of Externally-Controlled Format String",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "User-controlled input is passed directly as the format argument to printf/sprintf/syslog rather than as a %s argument.",
        "attack_scenario": "Attacker sends '%x%x%x%x' in a parameter; the server leaks stack data via printf(user_input).",
        "remediation_steps": [
            "Always use printf(\"%s\", user_input) — never pass user input as the format argument.",
            "Compile with -Wformat -Wformat-security -Werror=format-security.",
            "Replace syslog(user_input) with syslog(LOG_ERR, \"%s\", user_input).",
        ],
        "fix_code_example": "/* BEFORE */ printf(user_input);\n/* AFTER */ printf(\"%s\", user_input);",
        "verification": ["Send '%x%x%x%x' — if hex values appear in response, format string confirmed."],
    },

    "PATH_TRAVERSAL": {
        "title_pattern": "path traversal", "cwe_id": "CWE-22", "cwe_name": "Path Traversal",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "cvss_score": "7.5", "cvss_severity": "HIGH",
        "root_cause": "User-supplied file paths are concatenated into filesystem access calls without sanitizing '../' sequences.",
        "attack_scenario": "GET /cgi-bin/download?file=../../../etc/shadow reads /etc/shadow instead of the intended file.",
        "remediation_steps": [
            "Resolve canonical path with realpath() and verify it starts with the allowed base directory.",
            "Reject any input containing '../' or '..\\' before filesystem access.",
        ],
        "fix_code_example": "/* BEFORE */ fopen(user_path, \"r\");\n/* AFTER */\nchar *r = realpath(user_path, NULL);\nif (!r || strncmp(r, \"/www/\", 5)) { free(r); return 403; }",
        "verification": ["Request ../etc/passwd — after fix must return 403 or 404."],
    },

    "SQL_INJECTION": {
        "title_pattern": "sql injection", "cwe_id": "CWE-89", "cwe_name": "SQL Injection",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "SQL queries are constructed by string concatenation of user input without parameterized queries.",
        "attack_scenario": "POST /cgi-bin/admin with username=admin' OR '1'='1 bypasses authentication.",
        "remediation_steps": [
            "Use parameterized queries: sqlite3_prepare_v2() with bound parameters.",
            "Never concatenate user input into SQL strings.",
        ],
        "fix_code_example": "/* BEFORE */ snprintf(q, sz, \"SELECT * FROM users WHERE name='%s'\", u); sqlite3_exec(db, q, ..);\n/* AFTER */ sqlite3_prepare_v2(db, \"SELECT * FROM users WHERE name=?1\", -1, &stmt, NULL); sqlite3_bind_text(stmt, 1, u, -1, SQLITE_STATIC);",
        "verification": ["Submit \"admin' OR '1'='1\" — if bypassed, injection confirmed."],
    },

    "XSS_REFLECTED": {
        "title_pattern": "xss", "cwe_id": "CWE-79", "cwe_name": "Cross-Site Scripting",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:N",
        "cvss_score": "8.3", "cvss_severity": "HIGH",
        "root_cause": "The web management UI reflects user input in HTML output without HTML entity escaping.",
        "attack_scenario": "Attacker crafts <script>alert(1)</script> in a parameter that the admin UI echoes.",
        "remediation_steps": [
            "HTML-escape all output: < → &lt; > → &gt; \" → &quot; ' → &#x27;",
            "Add Content-Security-Policy header: default-src 'self'.",
        ],
        "fix_code_example": "/* BEFORE */ printf(\"<div>%s</div>\", user_name);\n/* AFTER */ html_escape(user_name, safe, sizeof(safe)); printf(\"<div>%s</div>\", safe);",
        "verification": ["Submit <script>alert('XSS')</script> — after fix must appear as literal text, not execute."],
    },

    "CSRF": {
        "title_pattern": "csrf", "cwe_id": "CWE-352", "cwe_name": "Cross-Site Request Forgery",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
        "cvss_score": "8.8", "cvss_severity": "HIGH",
        "root_cause": "State-changing endpoints lack anti-CSRF tokens and do not validate Origin/Referer headers.",
        "attack_scenario": "Attacker hosts a page with a hidden form that POSTs to the router admin interface.",
        "remediation_steps": [
            "Generate unique CSRF token per session; require on all state-changing POST requests.",
            "Set SameSite=Strict on session cookies.",
        ],
        "fix_code_example": "/* Add hidden CSRF token to forms */\n<input type=\"hidden\" name=\"csrf_token\" value=\"<?=csrf_token?>\">\n/* Server validates: */ if (strcmp(req_token, sess_token)) return 403;",
        "verification": ["Submit POST without token — must return 403."],
    },

    "SSRF": {
        "title_pattern": "ssrf", "cwe_id": "CWE-918", "cwe_name": "Server-Side Request Forgery",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N",
        "cvss_score": "8.6", "cvss_severity": "HIGH",
        "root_cause": "A URL-fetching feature accepts user-controlled URLs without validating the destination IP.",
        "attack_scenario": "Attacker sets NTP server to http://169.254.169.254/ — device requests cloud metadata, leaking credentials.",
        "remediation_steps": [
            "Validate destination IP: reject private/loopback/link-local (127.0.0.0/8, 10.0.0.0/8, 169.254.0.0/16).",
            "Use a URL allowlist of permitted external hosts.",
        ],
        "fix_code_example": "/* BEFORE */ curl_easy_setopt(curl, CURLOPT_URL, user_url);\n/* AFTER */ if (!is_allowed_url(user_url)) return 400; curl_easy_setopt(curl, CURLOPT_URL, user_url);",
        "verification": ["Set URL to http://127.0.0.1:8080/ — must be rejected."],
    },

    "INSECURE_DESERIALIZATION": {
        "title_pattern": "deserial", "cwe_id": "CWE-502", "cwe_name": "Deserialization of Untrusted Data",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "Configuration data (JSON/XML/binary blob) is deserialized without schema validation or signature verification.",
        "attack_scenario": "Attacker uploads crafted config.img containing a serialized payload that triggers code execution at boot.",
        "remediation_steps": [
            "Validate all deserialized fields against a strict schema before use.",
            "Sign configuration files with HMAC-SHA256; verify before deserializing.",
        ],
        "fix_code_example": "/* BEFORE */ memcpy(&config, uploaded_data, sizeof(config));\n/* AFTER */ if (!validate_hmac(uploaded_data, len)) return 400; if (parse_config_safe(uploaded_data, len, &cfg)) return 400;",
        "verification": ["Upload config with invalid HMAC — must be rejected."],
    },

    "INTEGER_OVERFLOW": {
        "title_pattern": "integer overflow", "cwe_id": "CWE-190", "cwe_name": "Integer Overflow",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "Arithmetic on user-controlled integers without overflow checks leads to undersized allocations.",
        "attack_scenario": "Attacker sends size=0xFFFFFFFF; size+header overflows to small value, allocates tiny buffer, memcpy overflows.",
        "remediation_steps": [
            "Check overflow before arithmetic: if (a > SIZE_MAX - b) error;",
            "Use compiler builtins: __builtin_add_overflow(), __builtin_mul_overflow().",
        ],
        "fix_code_example": "/* BEFORE */ size_t s = user_size + hdr; buf = malloc(s);\n/* AFTER */ if (__builtin_add_overflow(user_size, hdr, &s)) return NULL; buf = malloc(s);",
        "verification": ["Submit size=0xFFFFFFFF — must return error, not crash."],
    },

    "USE_AFTER_FREE": {
        "title_pattern": "use after free", "cwe_id": "CWE-416", "cwe_name": "Use After Free",
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "8.1", "cvss_severity": "HIGH",
        "root_cause": "A heap object is freed while references still exist; reallocated memory is then accessed through the dangling pointer.",
        "attack_scenario": "Network daemon frees connection on timeout but doesn't NULL pointer; new connection at same address is corrupted by old handler.",
        "remediation_steps": [
            "Set pointers to NULL immediately after free().",
            "Run with AddressSanitizer (-fsanitize=address) during testing.",
        ],
        "fix_code_example": "/* BEFORE */ free(conn->buf);\n/* AFTER */ free(conn->buf); conn->buf = NULL;",
        "verification": ["Run under ASAN — detects UAF at runtime.", "Rapid connect/disconnect cycles."],
    },

    "RACE_CONDITION": {
        "title_pattern": "race", "cwe_id": "CWE-367", "cwe_name": "TOCTOU Race Condition",
        "cvss_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "8.1", "cvss_severity": "HIGH",
        "root_cause": "Check and use happen in separate steps; state can change between them. Common in init scripts and /tmp handling.",
        "attack_scenario": "Firmware update checks signature of /tmp/update.bin, then executes it — attacker replaces file between check and exec.",
        "remediation_steps": [
            "Use atomic operations: open with O_NOFOLLOW, then fstat+validate on the fd.",
            "Perform operations on a private copy, not shared paths.",
        ],
        "fix_code_example": "/* BEFORE */ if (access(\"/tmp/u.bin\", R_OK)==0) system(\"/tmp/u.bin\");\n/* AFTER */ fd=open(\"/tmp/u.bin\", O_RDONLY|O_NOFOLLOW); if (fd<0) return; fstat(fd,&st); validate(fd);",
        "verification": ["Parallel process continuously replaces target file during check-to-use window."],
    },

    "WEAK_CRYPTO": {
        "title_pattern": "hardcoded key", "cwe_id": "CWE-321", "cwe_name": "Hard-coded Cryptographic Key",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "Firmware contains hardcoded AES/RSA/HMAC keys; all devices share the same key. One extraction compromises the fleet.",
        "attack_scenario": "Extract firmware → find static AES-128 key → decrypt updates for all devices.",
        "remediation_steps": [
            "Generate unique per-device key at manufacturing; store in TPM/secure element.",
            "Use HKDF with device-unique identifier + factory secret.",
        ],
        "fix_code_example": "/* BEFORE */ static uint8_t key[16] = {0xDE,0xAD,...};\n/* AFTER */ se_read(SE_KEY_SLOT, key, 16); /* From secure element */",
        "verification": ["strings firmware.bin | grep -E '[0-9a-fA-F]{32,}'", "Check if same key across versions."],
    },

    "MISSING_AUTH": {
        "title_pattern": "auth bypass", "cwe_id": "CWE-306", "cwe_name": "Missing Authentication for Critical Function",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "Critical endpoint lacks authentication entirely, or check can be bypassed by omitting headers or special values.",
        "attack_scenario": "POST /cgi-bin/upload_firmware without auth cookie — succeeds because only checks header presence, not validity.",
        "remediation_steps": [
            "Require cryptographically-signed session tokens on all non-public endpoints.",
            "Apply auth middleware globally; every endpoint must opt-in to being public.",
        ],
        "fix_code_example": "/* BEFORE */ handle_upload(req); /* No auth check */\n/* AFTER */ if (!verify_session(req->cookie)) return 401; handle_upload(req);",
        "verification": ["Access every endpoint without auth headers — must all return 401."],
    },

    "DEBUG_INFO_LEAK": {
        "title_pattern": "debug", "cwe_id": "CWE-489", "cwe_name": "Active Debug Code",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "cvss_score": "7.5", "cvss_severity": "HIGH",
        "root_cause": "Production firmware ships with debug endpoints, test handlers, verbose errors, or enabled JTAG/SWD.",
        "attack_scenario": "/cgi-bin/debug?cmd=show_config dumps WiFi passwords and admin credentials in plaintext.",
        "remediation_steps": [
            "Strip all debug endpoints from production builds via compile-time flags (#ifndef NDEBUG).",
            "Disable JTAG/SWD in production fuses.",
        ],
        "fix_code_example": "#ifndef NDEBUG\nregister_handler(\"/debug\", debug_handler);\n#endif",
        "verification": ["Enumerate all endpoints; try /debug, /test, /admin/debug.", "Verify JTAG/SWD pins disabled."],
    },

    "SENSITIVE_DATA_EXPOSURE": {
        "title_pattern": "password in", "cwe_id": "CWE-312", "cwe_name": "Cleartext Storage",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "cvss_score": "7.5", "cvss_severity": "HIGH",
        "root_cause": "Passwords, API tokens, private keys stored in plaintext in firmware filesystem or NVRAM.",
        "attack_scenario": "Extract rootfs → read /etc/shadow or /etc/config/wifi.cfg → plaintext admin/WPA passwords.",
        "remediation_steps": [
            "Hash passwords with bcrypt/scrypt/argon2; never store plaintext.",
            "Encrypt sensitive config with device-unique key from TPM/secure element.",
        ],
        "fix_code_example": "/* BEFORE */ fprintf(cfg, \"admin_pw=%s\\n\", pw);\n/* AFTER */ crypt_hashpw(pw, gensalt(12), hash); fprintf(cfg, \"admin_hash=%s\\n\", hash);",
        "verification": ["grep -r 'password\\|secret\\|key\\|token' rootfs/", "Attempt to use found credentials on live device."],
    },

    "IMPROPER_INPUT_VALIDATION": {
        "title_pattern": "input validation", "cwe_id": "CWE-20", "cwe_name": "Improper Input Validation",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "9.8", "cvss_severity": "CRITICAL",
        "root_cause": "User input accepted without validating type, length, range, or character set. Root cause of many vulnerability classes.",
        "attack_scenario": "Negative content-length, JSON number where string expected, 10MB value in 32-byte field → crash/OOM/misinterpretation.",
        "remediation_steps": [
            "Define and enforce input schemas at every external interface boundary.",
            "Limit maximum request size (body, headers, individual fields).",
            "Use safe integer parsing: strtol with errno check, never atoi.",
        ],
        "fix_code_example": "/* BEFORE */ int s = atoi(req->content_length); void *b = malloc(s);\n/* AFTER */ long s = strtol(req->content_length, &end, 10); if (*end || s<=0 || s>MAX) return 400; void *b = malloc((size_t)s);",
        "verification": ["Fuzz every parameter with 0, -1, MAX_INT, empty, and very long values.", "Verify 400 responses, not crashes."],
    },

    # ── Generic fallback ─────────────────────────────────────────────
    "GENERIC": {
        "title_pattern": "",
        "cwe_id": "CWE-0",
        "cwe_name": "Undetermined",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        "cvss_score": "0.0",
        "cvss_severity": "UNKNOWN",
        "root_cause": (
            "The vulnerability was identified through static analysis of the "
            "firmware artifact. Further dynamic validation is required to "
            "determine the precise root cause and exploitability."
        ),
        "attack_scenario": "Not yet determined — requires emulation-backed validation.",
        "remediation_steps": [
            "Conduct a full dynamic analysis of the affected component in a QEMU-emulated environment.",
            "Apply secure coding review to the identified binary or script.",
        ],
        "fix_code_example": "/* Insert fix after dynamic analysis */",
        "verification": ["Verify the fix in the emulated environment before deploying to hardware."],
    },
}


def match_remediation_template(
    finding_title: str,
    finding_evidence: list[str] | None = None,
) -> dict[str, Any]:
    """Return the best-matching remediation template for a finding.

    Matching is done by scoring the finding title and evidence against
    each template's `title_pattern` keyword.
    """
    combined = str(finding_title or "").lower()
    for line in (finding_evidence or []):
        combined += " " + str(line).lower()

    best_template = REMEDIATION_TEMPLATES["GENERIC"]
    best_score = 0

    for _key, template in REMEDIATION_TEMPLATES.items():
        pattern = str(template.get("title_pattern", "")).lower()
        if not pattern:
            continue
        score = combined.count(pattern)
        if score > best_score:
            best_score = score
            best_template = template

    return best_template


def format_remediation_for_prompt(template: dict[str, Any]) -> str:
    """Render a remediation template as a markdown block for LLM prompts."""
    lines = [
        "## Vulnerability Classification",
        f"- **CWE**: [{template['cwe_id']}] {template['cwe_name']}",
        f"- **CVSS 3.1 Vector**: `{template['cvss_vector']}`",
        f"- **CVSS Score**: {template['cvss_score']} ({template['cvss_severity']})",
        "",
        "## Root Cause Analysis",
        template["root_cause"],
        "",
        "## Attack Scenario",
        template["attack_scenario"],
        "",
        "## Remediation Steps",
    ]
    for i, step in enumerate(template["remediation_steps"], start=1):
        lines.append(f"{i}. {step}")
    lines.extend([
        "",
        "## Fix Code Example",
        "```c",
        template["fix_code_example"],
        "```",
        "",
        "## Post-Fix Verification",
    ])
    for i, step in enumerate(template["verification"], start=1):
        lines.append(f"- {step}")
    return "\n".join(lines)


def remediation_context_for_findings(
    findings: list[dict[str, Any]],
) -> str:
    """Build a consolidated remediation context block for all findings.

    Used by ReportAgent to inject remediation advice into the final report.
    """
    if not findings:
        return ""

    blocks: list[str] = []
    seen_templates: set[str] = set()

    for finding in findings:
        if not isinstance(finding, dict):
            continue
        title = str(finding.get("title", "")).strip()
        evidence = list(finding.get("evidence", []))
        template = match_remediation_template(title, evidence)
        template_key = template.get("cwe_id", "")
        if template_key in seen_templates:
            continue
        seen_templates.add(template_key)
        blocks.append(format_remediation_for_prompt(template))

    return "\n\n---\n\n".join(blocks)


def cvss_score_for_finding(finding: dict[str, Any]) -> str:
    """Return the CVSS score string for a finding."""
    title = str(finding.get("title", "")).strip()
    evidence = list(finding.get("evidence", []))
    template = match_remediation_template(title, evidence)
    return str(template.get("cvss_score", "0.0"))


def cwe_for_finding(finding: dict[str, Any]) -> str:
    """Return the CWE identifier for a finding."""
    title = str(finding.get("title", "")).strip()
    evidence = list(finding.get("evidence", []))
    template = match_remediation_template(title, evidence)
    return f"{template.get('cwe_id', 'CWE-0')} — {template.get('cwe_name', 'Undetermined')}"
